module.exports = [
  {
    id: 'ep7YpbXoz2saKU18bLTM3Q',
    alias: 'imperial-river-company-maupin',
    name: 'Imperial River Company',
    image_url: 'https://s3-media1.fl.yelpcdn.com/bphoto/BSL_bPB9WxxNAkfGqH3c9w/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/imperial-river-company-maupin?adjust_creative=PjvJql1F1kyGCOnrBRz5Gw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=PjvJql1F1kyGCOnrBRz5Gw',
    review_count: 56,
    categories: [
      {
        alias: 'hotels',
        title: 'Hotels',
      },
      {
        alias: 'tradamerican',
        title: 'American (Traditional)',
      },
      {
        alias: 'rafting',
        title: 'Rafting/Kayaking',
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 45.1725035692351,
      longitude: -121.074979611856,
    },
    transactions: [],
    price: '$$',
    location: {
      address1: '304 Bakeoven County Rd',
      address2: '',
      address3: '',
      city: 'Maupin',
      zip_code: '97037',
      country: 'US',
      state: 'OR',
      display_address: [
        '304 Bakeoven County Rd',
        'Maupin, OR 97037',
      ],
    },
    phone: '+15413952404',
    display_phone: '(541) 395-2404',
    distance: 39081.138871572766,
  },
  {
    id: 'QkkhaTWx58ab54Yg-QyQxQ',
    alias: 'the-riverside-maupin',
    name: 'The Riverside',
    image_url: 'https://s3-media2.fl.yelpcdn.com/bphoto/WgnBQoI93NFSObuuGjzW9w/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/the-riverside-maupin?adjust_creative=PjvJql1F1kyGCOnrBRz5Gw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=PjvJql1F1kyGCOnrBRz5Gw',
    review_count: 25,
    categories: [
      {
        alias: 'tradamerican',
        title: 'American (Traditional)',
      },
    ],
    rating: 5,
    coordinates: {
      latitude: 45.1707523795975,
      longitude: -121.077980751687,
    },
    transactions: [],
    price: '$$',
    location: {
      address1: '597 S Hwy 197',
      address2: '',
      address3: '',
      city: 'Maupin',
      zip_code: '97037',
      country: 'US',
      state: 'OR',
      display_address: [
        '597 S Hwy 197',
        'Maupin, OR 97037',
      ],
    },
    phone: '+15413952438',
    display_phone: '(541) 395-2438',
    distance: 39133.66467983177,
  },
  {
    id: 'XPyRMVEZbhoHDVS4gvZ0gQ',
    alias: 'henrys-deli-mart-maupin',
    name: "Henry's Deli-Mart",
    image_url: 'https://s3-media1.fl.yelpcdn.com/bphoto/_747cn50V_T9-5q5jGz0wA/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/henrys-deli-mart-maupin?adjust_creative=PjvJql1F1kyGCOnrBRz5Gw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=PjvJql1F1kyGCOnrBRz5Gw',
    review_count: 9,
    categories: [
      {
        alias: 'delis',
        title: 'Delis',
      },
    ],
    rating: 5,
    coordinates: {
      latitude: 45.1740867530288,
      longitude: -121.076736835176,
    },
    transactions: [],
    price: '$',
    location: {
      address1: 'N Hwy 197',
      address2: '',
      address3: '',
      city: 'Maupin',
      zip_code: '97037',
      country: 'US',
      state: 'OR',
      display_address: [
        'N Hwy 197',
        'Maupin, OR 97037',
      ],
    },
    phone: '+15413952278',
    display_phone: '(541) 395-2278',
    distance: 39300.391882050164,
  },
  {
    id: 'NkiNhmqvu1XVck0kaWQgLg',
    alias: 'shaniko-cafe-shaniko',
    name: 'Shaniko Cafe',
    image_url: '',
    is_closed: false,
    url: 'https://www.yelp.com/biz/shaniko-cafe-shaniko?adjust_creative=PjvJql1F1kyGCOnrBRz5Gw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=PjvJql1F1kyGCOnrBRz5Gw',
    review_count: 1,
    categories: [
      {
        alias: 'restaurants',
        title: 'Restaurants',
      },
    ],
    rating: 4,
    coordinates: {
      latitude: 45.0034,
      longitude: -120.75252,
    },
    transactions: [],
    price: '$',
    location: {
      address1: '4TH E St',
      address2: '',
      address3: '',
      city: 'Shaniko',
      zip_code: '97057',
      country: 'US',
      state: 'OR',
      display_address: [
        '4TH E St',
        'Shaniko, OR 97057',
      ],
    },
    phone: '+15414893415',
    display_phone: '(541) 489-3415',
    distance: 7893.329603903392,
  },
  {
    id: '8NfYYTxDMF2kZArM5kGnuw',
    alias: 'rainbow-tavern-maupin',
    name: 'Rainbow Tavern',
    image_url: 'https://s3-media3.fl.yelpcdn.com/bphoto/BXx90hwN7knm4dmaqAWxvg/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/rainbow-tavern-maupin?adjust_creative=PjvJql1F1kyGCOnrBRz5Gw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=PjvJql1F1kyGCOnrBRz5Gw',
    review_count: 10,
    categories: [
      {
        alias: 'bars',
        title: 'Bars',
      },
      {
        alias: 'tradamerican',
        title: 'American (Traditional)',
      },
    ],
    rating: 3.5,
    coordinates: {
      latitude: 45.1752166748047,
      longitude: -121.080291748047,
    },
    transactions: [],
    price: '$$',
    location: {
      address1: '411 Deschutes Ave',
      address2: '',
      address3: '',
      city: 'Maupin',
      zip_code: '97037',
      country: 'US',
      state: 'OR',
      display_address: [
        '411 Deschutes Ave',
        'Maupin, OR 97037',
      ],
    },
    phone: '+15413952497',
    display_phone: '(541) 395-2497',
    distance: 39606.12252163088,
  },
  {
    id: 'Mw3VIB1BHzKnAkwBnb9AGA',
    alias: 'maupin-market-maupin',
    name: 'Maupin Market',
    image_url: 'https://s3-media3.fl.yelpcdn.com/bphoto/qae_kqsIjxUIF_JyXlaF-A/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/maupin-market-maupin?adjust_creative=PjvJql1F1kyGCOnrBRz5Gw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=PjvJql1F1kyGCOnrBRz5Gw',
    review_count: 4,
    categories: [
      {
        alias: 'grocery',
        title: 'Grocery',
      },
      {
        alias: 'delis',
        title: 'Delis',
      },
      {
        alias: 'beer_and_wine',
        title: 'Beer, Wine & Spirits',
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 45.1751663535833,
      longitude: -121.080944538116,
    },
    transactions: [],
    price: '$$$',
    location: {
      address1: '507 Deschutes Ave',
      address2: '',
      address3: '',
      city: 'Maupin',
      zip_code: '97037',
      country: 'US',
      state: 'OR',
      display_address: [
        '507 Deschutes Ave',
        'Maupin, OR 97037',
      ],
    },
    phone: '+15413952888',
    display_phone: '(541) 395-2888',
    distance: 39628.782823463676,
  },
];
